### ISSUE TITLE
"Component for use in RGI sequences. Isolated images should ..." in some "keywords" properties (and ⊛ is in some emoji names)

### ISSUE THREAD

**Issue by josephrocca** [amio/emoji.json#10]
Hi, thanks for the great little dataset! Just a heads up that:

* The "red hair" and many others contain some bad data in the "keywords" property: "Component for use in RGI sequences. Isolated images should ...". Looks like it should be easy to filter out since these notes seem to consistently come after a new line character. See another example of this in the "safety vest" entry: "Used in a ZWJ sequence for service dog"

* "guide dog" and many others contain the "new emoji" symbol (⊛) in their name.

Cheers!

**Comment by amio** [comment]
@josephrocca Thanks for reporting!

**Comment by amio** [comment]
Should be fixed in latest [12.1.0](https://github.com/amio/emoji.json/releases/tag/v12.1.0)
