### ISSUE TITLE
Twemoji

### ISSUE THREAD

**Issue by supertiger1234** [amio/emoji.json#5]
im trying to use this with twemoji so i can use ```:ok_hand:``` and stuff but i noticed that some names are missing. twemoji has 2000 + emojis hmmm

**Comment by amio** [comment]
emoji.json has 3836 emojis in [v12.1.0](https://github.com/amio/emoji.json/releases/tag/v12.1.0), I guess it should cover all emojis now.

Feel free to reopen this if you found anything missing.
